services:
  postgres:
    image: postgres:16-alpine
    container_name: tinyledger-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tinyledger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: tinyledger-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
