services:
  postgres:
    image: postgres:18-alpine
    container_name: bank-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
